name: pineoclock_app
description: A flutter themed alarm app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  android_alarm_manager_plus: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flutter_analog_clock: ^1.0.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  alarm: ^4.1.1
  permission_handler: ^12.0.3
  flutter_overlay_window: ^0.4.2
  pedometer: ^4.0.2
  http: ^1.2.1
  flutter_earth_globe: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/